### ISSUE TITLE
Returns Cannot GET/

### ISSUE THREAD

**Issue by juanr2001** [wladiston/sails-browsersync-example#1]
For some reason your middleware implementations for connectLivereload, return cannot get when the sails lift is initiated.

**Comment by sudhirjena** [comment]
Hey @juanr2001, Thanks for highlighting this issue. Although I am not a maintainer on this repository, I encountered the same issue. I discovered that the solution is in 

https://github.com/wladiston/sails-browsersync-example/blob/master/config/http.js

The undocumented part which leads to this confusion is that you have to uncomment middleware order in config/http.js for the connect-livereload to work.

```
...
order: [
      'startRequestTimer',
      'cookieParser',
      'session',
      'connectLivereload',
      'myRequestLogger',
      //'bodyParser',
      'handleBodyParserError',
      'compress',
      'methodOverride',
      'poweredBy',
      '$custom',
      'router',
      'www',
      'favicon',
      '404',
      '500'
    ],
...
```

**Comment by wladiston** [comment]
Sorry for the late reply.
Yeap, you just need to make sure the middleware is in the **order** array. I'll change the documentation to make it clear. Thanks for the reply @sudhirjena.
